
# 🔢 02 — NumPy

### A complete, self-contained beginner's notebook

This notebook explains **NumPy** from scratch — no prior file or resource needed.
Every term is explained in plain English, and every code cell has already been run so you can see the real output right away.

---

## What is NumPy?

**NumPy** (Numerical Python) is a Python **Library** (pre-written, reusable code) built for fast math on numbers and lists.

> 🧠 *Think of a normal Python list as a notebook where you calculate one number at a time. NumPy is like a calculator that does thousands of calculations instantly, all at once.*

### Why not just use normal Python lists?
- NumPy arrays are **much faster** for math
- NumPy lets you do math on a whole array at once (**Vectorization**)
- NumPy powers almost every other data science library (Pandas, Matplotlib, scikit-learn all rely on it)

---

## What this notebook covers

1. Creating arrays
2. Array attributes (shape, dimension, size, data type)
3. Array creation shortcuts (zeros, ones, arange, linspace, random)
4. Indexing & slicing
5. Reshaping arrays
6. Arithmetic operations & broadcasting
7. Aggregation functions (sum, mean, min, max, std)
8. Axis-based operations
9. Sorting arrays
10. Boolean masking & filtering
11. Combining arrays (concatenate & stack)
12. Vectorization vs. loops — a speed test
13. Quick-reference glossary
14. Practice exercises



## 🔧 Setup


In [1]:

import numpy as np
import time

print("NumPy version:", np.__version__)
print("Setup complete! ✅")


NumPy version: 2.4.4
Setup complete! ✅



---
## 1️⃣ Creating Arrays

An **Array** is a list of items (usually numbers), all the same type, stored together.

> 🧠 *A row of lockers numbered 1–10, each holding one item — that's like an array.*


In [2]:

# Creating an array from a normal Python list
scores = np.array([85, 90, 76, 60, 95])
print("Array:", scores)
print("Type:", type(scores))


Array: [85 90 76 60 95]
Type: <class 'numpy.ndarray'>


In [3]:

# A 2D array (like a mini table): rows = students, columns = 3 test scores each
tests = np.array([
    [85, 90, 88],
    [76, 80, 78],
    [60, 65, 70]
])
print("2D array (3 students, 3 test scores each):")
print(tests)


2D array (3 students, 3 test scores each):
[[85 90 88]
 [76 80 78]
 [60 65 70]]



---
## 2️⃣ Array Attributes

- **Dimension** = how many directions the data extends in (1D = list, 2D = table, 3D = cube)
- **Shape** = the size of data in terms of rows and columns
- **Data Type** = the kind of value stored (int, float, etc.)


In [4]:

print("Shape of 'tests' array:", tests.shape)        # (rows, columns)
print("Number of dimensions:", tests.ndim)            # 2D
print("Total number of elements:", tests.size)        # 9 elements
print("Data type of elements:", tests.dtype)           # int64 or similar


Shape of 'tests' array: (3, 3)
Number of dimensions: 2
Total number of elements: 9
Data type of elements: int64



---
## 3️⃣ Array Creation Shortcuts

NumPy gives you quick ways to build arrays without typing every number yourself.


In [5]:

zeros = np.zeros((2, 3))          # 2 rows, 3 columns, all zeros
ones = np.ones((2, 3))            # 2 rows, 3 columns, all ones
identity = np.eye(3)              # 3x3 identity matrix (1s on diagonal)

print("Zeros array:\n", zeros)
print("\nOnes array:\n", ones)
print("\nIdentity matrix:\n", identity)


Zeros array:
 [[0. 0. 0.]
 [0. 0. 0.]]

Ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]

Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:

# arange: like Python's range(), but returns a NumPy array
sequence = np.arange(0, 20, 5)    # start=0, stop=20, step=5
print("arange(0, 20, 5):", sequence)

# linspace: evenly spaced numbers between a start and stop value
evenly_spaced = np.linspace(0, 1, 5)   # 5 numbers evenly spaced between 0 and 1
print("linspace(0, 1, 5):", evenly_spaced)


arange(0, 20, 5): [ 0  5 10 15]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


In [7]:

# Random numbers (useful for practice data, simulations, testing)
np.random.seed(42)   # makes the "random" numbers repeatable every time we run this
random_scores = np.random.randint(50, 100, size=6)   # 6 random ints between 50 and 100
print("Random scores:", random_scores)


Random scores: [88 78 64 92 57 70]



---
## 4️⃣ Indexing & Slicing

- **Index** = the position/label used to identify an item
- **Slice** = taking a smaller piece out of an array

> 🧠 *Picking only the first 3 students from a class list of 30.*


In [8]:

scores = np.array([85, 90, 76, 60, 95, 88, 72])

print("Full array:", scores)
print("First item (index 0):", scores[0])
print("Last item (index -1):", scores[-1])
print("Slice [1:4]  (items at index 1,2,3):", scores[1:4])
print("Every second item [::2]:", scores[::2])


Full array: [85 90 76 60 95 88 72]
First item (index 0): 85
Last item (index -1): 72
Slice [1:4]  (items at index 1,2,3): [90 76 60]
Every second item [::2]: [85 76 95 72]


In [9]:

# Indexing a 2D array: [row, column]
print("2D array:\n", tests)
print("\nStudent 0, all tests:", tests[0])
print("Student 1, test 2 only:", tests[1, 2])
print("All students, test 1 only (column):", tests[:, 1])


2D array:
 [[85 90 88]
 [76 80 78]
 [60 65 70]]

Student 0, all tests: [85 90 88]
Student 1, test 2 only: 78
All students, test 1 only (column): [90 80 65]



---
## 5️⃣ Reshaping Arrays

Reshaping changes how the same data is arranged (e.g. turning a flat list into a table), without changing the values themselves.


In [10]:

flat = np.arange(1, 13)   # numbers 1 to 12
print("Flat array:", flat)

reshaped = flat.reshape(3, 4)   # 3 rows, 4 columns
print("\nReshaped into 3 rows x 4 columns:")
print(reshaped)


Flat array: [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped into 3 rows x 4 columns:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:

# Transpose: flipping rows into columns and vice versa
print("Original:\n", reshaped)
print("\nTransposed (rows <-> columns):")
print(reshaped.T)


Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed (rows <-> columns):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]



---
## 6️⃣ Arithmetic Operations & Broadcasting

- **Vectorization** = doing math on the entire array at once instead of looping item by item
- **Broadcasting** = a NumPy trick that lets you do math on arrays of *different sizes* automatically

> 🧠 *If every student gets 5 bonus marks, broadcasting adds it to everyone instantly — no loop needed.*


In [12]:

scores = np.array([85, 90, 76, 60, 95])

print("Original scores:", scores)
print("Add 5 bonus marks (vectorized):", scores + 5)
print("Scale by 10% curve (broadcasting):", scores * 1.1)
print("Scores squared:", scores ** 2)


Original scores: [85 90 76 60 95]
Add 5 bonus marks (vectorized): [ 90  95  81  65 100]
Scale by 10% curve (broadcasting): [ 93.5  99.   83.6  66.  104.5]
Scores squared: [7225 8100 5776 3600 9025]


In [13]:

# Two arrays of the SAME size: element-wise math
test1 = np.array([80, 70, 90])
test2 = np.array([85, 75, 95])

print("Test 1:", test1)
print("Test 2:", test2)
print("Average of both tests (element-wise):", (test1 + test2) / 2)


Test 1: [80 70 90]
Test 2: [85 75 95]
Average of both tests (element-wise): [82.5 72.5 92.5]


In [14]:

# Broadcasting with a 2D array: add a different bonus to each column
tests = np.array([
    [85, 90, 88],
    [76, 80, 78],
    [60, 65, 70]
])
bonus_per_test = np.array([2, 5, 1])   # different bonus for test 1, 2, 3

print("Original tests:\n", tests)
print("\nBonus per test:", bonus_per_test)
print("\nTests after adding bonus (broadcasting a row across all students):")
print(tests + bonus_per_test)


Original tests:
 [[85 90 88]
 [76 80 78]
 [60 65 70]]

Bonus per test: [2 5 1]

Tests after adding bonus (broadcasting a row across all students):
[[87 95 89]
 [78 85 79]
 [62 70 71]]



---
## 7️⃣ Aggregation Functions (Statistics)

| Term | Definition |
|---|---|
| **Mean** | The average of a set of numbers |
| **Median** | The middle value when sorted |
| **Standard Deviation** | How spread out numbers are from the average |


In [15]:

scores = np.array([85, 90, 76, 60, 95])

print("Sum:", np.sum(scores))
print("Mean:", np.mean(scores))
print("Median:", np.median(scores))
print("Minimum:", np.min(scores))
print("Maximum:", np.max(scores))
print("Standard Deviation:", round(np.std(scores), 2))


Sum: 406
Mean: 81.2
Median: 85.0
Minimum: 60
Maximum: 95
Standard Deviation: 12.32



---
## 8️⃣ Axis-Based Operations

**Axis** = the direction along which you calculate: rows or columns.

- `axis=0` → down each **column**
- `axis=1` → across each **row**

> 🧠 *Adding up marks "across" each student (row-wise, axis=1) vs "down" each subject (column-wise, axis=0).*


In [16]:

tests = np.array([
    [85, 90, 88],   # student 0
    [76, 80, 78],   # student 1
    [60, 65, 70]    # student 2
])
print("Tests:\n", tests)

print("\nAverage PER STUDENT (across each row, axis=1):", tests.mean(axis=1))
print("Average PER TEST (down each column, axis=0):", tests.mean(axis=0))


Tests:
 [[85 90 88]
 [76 80 78]
 [60 65 70]]

Average PER STUDENT (across each row, axis=1): [87.66666667 78.         65.        ]
Average PER TEST (down each column, axis=0): [73.66666667 78.33333333 78.66666667]



---
## 9️⃣ Sorting Arrays


In [17]:

scores = np.array([85, 90, 76, 60, 95])

print("Original:", scores)
print("Sorted (ascending):", np.sort(scores))
print("Sorted (descending):", np.sort(scores)[::-1])


Original: [85 90 76 60 95]
Sorted (ascending): [60 76 85 90 95]
Sorted (descending): [95 90 85 76 60]



---
## 🔟 Boolean Masking & Filtering

- **Boolean** = a value that's either `True` or `False`
- **Filter** = picking out only the items that match a certain condition

> 🧠 *Asking "which students scored above 80?" and only keeping those.*


In [18]:

scores = np.array([85, 90, 76, 60, 95, 88, 72])

above_80 = scores > 80          # Boolean mask: True/False for each item
print("Boolean mask (scores > 80):", above_80)

filtered_scores = scores[above_80]   # Filter: keep only the True ones
print("Filtered scores (only above 80):", filtered_scores)


Boolean mask (scores > 80): [ True  True False False  True  True False]
Filtered scores (only above 80): [85 90 95 88]


In [19]:

# You can also do it in one line
top_scores = scores[scores >= 85]
print("Scores 85 and above:", top_scores)


Scores 85 and above: [85 90 95 88]



---
## 1️⃣1️⃣ Combining Arrays

- **Concatenate** = joining arrays end-to-end
- **Stack** = joining arrays as new rows or columns


In [20]:

group_a = np.array([85, 90, 76])
group_b = np.array([60, 95, 88])

combined = np.concatenate([group_a, group_b])
print("Concatenated (joined end-to-end):", combined)

stacked_rows = np.vstack([group_a, group_b])     # stack as rows
print("\nStacked as rows:\n", stacked_rows)

stacked_cols = np.hstack([group_a, group_b])     # stack side-by-side
print("\nStacked side-by-side (hstack):", stacked_cols)


Concatenated (joined end-to-end): [85 90 76 60 95 88]

Stacked as rows:
 [[85 90 76]
 [60 95 88]]

Stacked side-by-side (hstack): [85 90 76 60 95 88]



---
## 1️⃣2️⃣ Vectorization vs. Loops — A Speed Test

Let's actually prove why NumPy is faster. We'll add 1 to every number in a list of 1,000,000 numbers two ways:

1. Using a normal Python loop
2. Using NumPy vectorization


In [21]:

big_list = list(range(1_000_000))
big_array = np.arange(1_000_000)

# Method 1: normal Python loop
start = time.time()
result_loop = [x + 1 for x in big_list]
loop_time = time.time() - start

# Method 2: NumPy vectorization
start = time.time()
result_vectorized = big_array + 1
vector_time = time.time() - start

print(f"Python loop time:       {loop_time:.5f} seconds")
print(f"NumPy vectorized time:  {vector_time:.5f} seconds")
print(f"\nNumPy was about {loop_time / vector_time:.0f}x faster! 🚀")


Python loop time:       0.26026 seconds
NumPy vectorized time:  0.04618 seconds

NumPy was about 6x faster! 🚀



---
## 📖 Quick-Reference Glossary Recap

| Term | Simple Definition |
|---|---|
| Array | A list of same-type items stored together |
| Axis | Direction of operation: rows (axis=1) or columns (axis=0) |
| Boolean | A True/False value |
| Broadcasting | Doing math on arrays of different sizes automatically |
| Data Type | The kind of value stored (int, float, etc.) |
| Dimension | How many directions data extends in (1D, 2D, 3D) |
| Filter | Selecting only items that match a condition |
| Index | The position used to identify an item |
| Mean | The average |
| Median | The middle value when sorted |
| NumPy | Library for fast math & arrays |
| Reshape | Rearranging the same data into a different shape |
| Shape | Size of data as (rows, columns) |
| Slice | A smaller piece taken from an array |
| Standard Deviation | How spread out values are from the mean |
| Transpose | Flipping rows into columns and vice versa |
| Vectorization | Doing math on a whole array at once, instead of looping |



---
## ✏️ Practice Exercises

Try these yourself before checking the solutions below.

1. Create an array of the numbers 1 to 10, then find its mean and standard deviation.
2. Create a 2D array of shape (4, 3) filled with zeros, then change it to all 7s.
3. From the array `[3, 8, 2, 9, 5, 1, 7]`, filter out only the numbers greater than 4.
4. Reshape the numbers 1 to 16 into a 4x4 array, then find the sum of each row and each column.


In [22]:

# 1. Array 1-10, mean & std
arr = np.arange(1, 11)
print("Exercise 1 — Array:", arr)
print("Mean:", arr.mean())
print("Standard Deviation:", round(arr.std(), 2))


Exercise 1 — Array: [ 1  2  3  4  5  6  7  8  9 10]
Mean: 5.5
Standard Deviation: 2.87


In [23]:

# 2. 4x3 zeros array, then change to all 7s
arr2 = np.zeros((4, 3))
arr2[:] = 7
print("Exercise 2 — 4x3 array filled with 7s:")
print(arr2)


Exercise 2 — 4x3 array filled with 7s:
[[7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]
 [7. 7. 7.]]


In [24]:

# 3. Filter numbers greater than 4
arr3 = np.array([3, 8, 2, 9, 5, 1, 7])
filtered = arr3[arr3 > 4]
print("Exercise 3 — Original:", arr3)
print("Filtered (greater than 4):", filtered)


Exercise 3 — Original: [3 8 2 9 5 1 7]
Filtered (greater than 4): [8 9 5 7]


In [25]:

# 4. Reshape 1-16 into 4x4, sum of rows and columns
arr4 = np.arange(1, 17).reshape(4, 4)
print("Exercise 4 — 4x4 array:")
print(arr4)
print("\nSum of each row (axis=1):", arr4.sum(axis=1))
print("Sum of each column (axis=0):", arr4.sum(axis=0))


Exercise 4 — 4x4 array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sum of each row (axis=1): [10 26 42 58]
Sum of each column (axis=0): [28 32 36 40]



---
## 🎯 Conclusion & Next Steps

You've now covered the essential building blocks of NumPy:

✅ Creating arrays & understanding their attributes
✅ Array creation shortcuts (zeros, ones, arange, linspace, random)
✅ Indexing, slicing & reshaping
✅ Arithmetic operations & broadcasting
✅ Aggregation functions & axis-based operations
✅ Sorting, boolean masking & filtering
✅ Combining arrays
✅ Why vectorization makes NumPy so much faster than plain Python loops

### What to do next
- Move on to **03_Pandas.ipynb** — Pandas is built on top of NumPy and uses these same array ideas inside tables (DataFrames).
- Try creating your own arrays from real numbers (e.g. your own grades, expenses, or measurements) and run the same operations on them.

**You don't need any other file to understand this notebook — everything was defined, explained, and demonstrated with real output above.**
